name: topchimp
favicon: null
layout_spectrum: 0.92676
typography_spectrum: 0.5329954854678363
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eeede9'
    - '#171314'
    - '#615d54'
    - '#df8f9a'
    - '#00768e'
  brandStrength: 0.625
  lightness: 0.10290662106126547
  saturation: 0.5
  rhythmicContrast: 0.47200983157381415
purpose: []
